### ISSUE TITLE
Documentation Bug-ish...

### ISSUE THREAD

**Issue by rodinholland** [zmoog/telegram-cli#5]
Hello!

Just downloaded and set up your program - very useful!

One small nit-pick: in your example startup documentation, you have an EXPORT where you set up the bot id to use. I found out that the bot id must start with the letters "bot" (sans quotes of course!) otherwise the Telegram REST API won't find it.

Just thought you'd like to know!

**Comment by rodinholland** [comment]
Buh - my bad! The Docs are in fact correct. A visual hallucination on my part!

Sorry!

**Comment by zmoog** [comment]
Hey, @rodinholland, thanks for using this small tool! I created it to automate some personal workflow, and I'm happy to learn that it's helpful to others!

**Comment by zmoog** [comment]
I'm closing this issue, but feel free to create others if you run into any problem!
